name: projeto_aps_front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  jwt_decode: ^0.3.1
  intl: ^0.20.2
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 
  logging: ^1.0.2
  image_picker: ^1.1.2
  file_picker: ^8.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true