spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        default_schema: projeto_aps
        #dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: optional:file:.env[.properties]

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG