spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    #driver-class-name: org.postgresql.Driver

  jpa:
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
        show_sql: false
        use_sql_comments: false
        format_sql: false
        default_schema: projeto_aps
        #dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: optional:file:.env[.properties]


server:
  port: 8080

#logging:
 # level:
  #  root: INFO
   # org.hibernate.SQL: DEBUG

logging:
  level:
    root: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF